In [1]:
import pandas as pd
import numpy as np

In [2]:
x1=np.random.randint(low=1,high=20,size=(50,))


x2=np.random.randint(low=1,high=20,size=(50,))

In [3]:
y=3+2*x1-4*x2+np.random.random((50,))

In [4]:
y

array([-50.53333535,   5.70085903,  -6.68095047, -34.67832281,
       -44.01840741,   9.91460269, -56.98875197,  -6.45046905,
       -40.13672383, -42.63014846,  37.49359643,   9.00220793,
       -10.6865236 , -22.53904073, -34.16582347, -30.18913769,
       -24.9034367 , -44.69501979, -34.90926479,  -8.94304841,
         5.25296366, -22.23795979, -10.31134385,  -8.9922582 ,
       -18.45028807, -18.09511293, -60.82256087, -48.19225941,
        17.12539764, -52.02441572,  -4.17472443,  27.85554232,
       -14.36152427, -10.67458013, -26.50375406,  23.61968364,
       -48.18736693,   5.91225088,   3.06547015, -32.88863941,
       -30.73399473,  -8.78411302,  -6.17356549, -48.85208201,
       -32.24954075, -30.34012473, -46.39029403,  11.06163246,
       -42.46903302,   7.15438748])

In [5]:
x1

array([ 5,  3, 17,  4, 18, 17,  1, 15, 19,  2, 10, 17, 11,  4, 18,  6, 17,
        2,  1, 10,  1,  9,  2, 19, 14,  1, 18, 10, 12, 10, 12, 18, 17, 11,
       12, 12, 19, 16,  9, 16, 18,  7,  4,  4, 10,  7, 10,  3, 11, 12])

In [6]:
x2

array([18, 14,  8,  8,  1, 18, 18, 12, 13, 14, 18,  5, 14,  3, 18, 19,  4,
       12, 12,  8, 19, 14,  5,  4,  6,  1, 11, 19,  3,  3,  1,  6,  9,  6,
       17, 15,  9, 15,  3,  7, 14, 12,  5, 15,  9,  4, 13,  8, 10, 15])

In [5]:


x=pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})

w=np.zeros(x.shape[1])

In [8]:
def myprediction(features,weights):

    predictions=np.dot(features,weights)
    return(predictions)

myprediction(x,w)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
def myerror(target,features,weights):
    error=target-myprediction(features,weights)
    return(error)

In [10]:
def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error)
    return(cost)

mycost(y,x,w)


46447.97902449577

In [11]:
def gradient(target,features,weights):
    
    error=myerror(target,features,weights)
    
    gradient=-np.dot(features.T,error)
    
    return(gradient)

gradient(y,x,w)

array([  951.89934604,  7282.23480553, 16087.24183104])

In [12]:
def my_lr(target,features,learning_rate):
    
    weights=np.zeros(features.shape[1])
    
    for i in np.arange(100000):
        weights -= learning_rate*gradient(target,features,weights)
        weights[0] -=10*learning_rate*gradient(target,features,weights)[0] # if you comment this out , your coefficient estimates will not be as good as sklearn, why?
        if i%100==0:
            print(mycost(target,features,weights),weights)
    return(weights)

my_lr(y,x,0.000001)

45808.4684399541 [-0.01034528 -0.00728223 -0.01608724]
20155.044427175864 [-0.56182222 -0.24647849 -1.0550645 ]
14285.666699683654 [-0.68100035 -0.07243916 -1.55846511]
10786.183151370153 [-0.68703686  0.1802996  -1.89067315]
8198.235076140878 [-0.66428534  0.4271182  -2.15196754]
6239.592040181498 [-0.63494381  0.64906325 -2.372203  ]
4753.953182416363 [-0.60476935  0.84412405 -2.56215992]
3626.809587940722 [-0.57518099  1.01438811 -2.72719683]
2771.5847931935305 [-0.54646257  1.16269007 -2.87091338]
2122.6259831364073 [-0.51860914  1.29176791 -2.99616211]
1630.1334080610538 [-0.49154956  1.40407753 -3.10535257]
1256.3313848043774 [-0.46520406  1.50177679 -3.20056356]
972.5650265748161 [-0.43949843  1.58675006 -3.28360034]
757.0980481375083 [-0.41436666  1.66063985 -3.35603385]
593.4422911615314 [-0.38975087  1.72487704 -3.41923191]
469.0905810554989 [-0.36560046  1.78070796 -3.47438574]
374.5555315535122 [-0.34187123  1.82921812 -3.52253281]
302.6404268591065 [-0.3185246   1.87135294

20.761196059063884 [ 1.66403157  2.07733587 -3.92339014]
20.573588445847736 [ 1.67399961  2.07690775 -3.92380013]
20.38816917539491 [ 1.68390933  2.07648214 -3.92420772]
20.204912721853958 [ 1.69376109  2.07605902 -3.92461293]
20.023793857119188 [ 1.70355523  2.07563838 -3.92501577]
19.8447876473569 [ 1.71329207  2.07522019 -3.92541625]
19.667869449573555 [ 1.72297196  2.07480445 -3.92581439]
19.493014908222843 [ 1.73259523  2.07439115 -3.9262102 ]
19.320199951852985 [ 1.74216221  2.07398026 -3.9266037 ]
19.149400789792804 [ 1.75167323  2.07357177 -3.92699489]
18.980593908876624 [ 1.76112862  2.07316567 -3.9273838 ]
18.813756070207376 [ 1.77052869  2.07276195 -3.92777043]
18.64886430595719 [ 1.77987379  2.07236059 -3.9281548 ]
18.485895916205806 [ 1.78916422  2.07196158 -3.92853692]
18.32482846581536 [ 1.79840031  2.0715649  -3.9289168 ]
18.165639781341923 [ 1.80758237  2.07117054 -3.92929447]
18.008307947982836 [ 1.81671073  2.07077849 -3.92966992]
17.852811306560323 [ 1.82578569  2.0

7.444751904006632 [ 2.661301    2.03450435 -3.96440841]
7.4124735106511235 [ 2.66543566  2.03432677 -3.96457848]
7.380571627541173 [ 2.66954614  2.03415023 -3.96474754]
7.34904186288552 [ 2.67363257  2.03397472 -3.96491562]
7.31787987612085 [ 2.67769511  2.03380024 -3.96508271]
7.287081377314077 [ 2.68173387  2.03362678 -3.96524883]
7.2566421265721575 [ 2.68574902  2.03345434 -3.96541398]
7.226557933457947 [ 2.68974068  2.0332829  -3.96557815]
7.196824656413497 [ 2.69370899  2.03311247 -3.96574137]
7.167438202190008 [ 2.69765409  2.03294303 -3.96590364]
7.138394525284241 [ 2.70157611  2.03277458 -3.96606495]
7.109689627381579 [ 2.70547519  2.03260712 -3.96622532]
7.081319556805584 [ 2.70935146  2.03244064 -3.96638476]
7.053280407974087 [ 2.71320506  2.03227513 -3.96654326]
7.025568320861353 [ 2.71703612  2.03211059 -3.96670083]
6.998179480466931 [ 2.72084477  2.03194702 -3.96685748]
6.9711101162901565 [ 2.72463114  2.0317844  -3.96701322]
6.944356501811285 [ 2.72839536  2.03162273 -3.9

5.153621948439558 [ 3.07496071  2.01673816 -3.98142248]
5.148068364233948 [ 3.07667574  2.0166645  -3.98149302]
5.142579559626573 [ 3.07838074  2.01659128 -3.98156315]
5.137154778997953 [ 3.08007576  2.01651848 -3.98163286]
5.131793275542493 [ 3.08176086  2.0164461  -3.98170217]
5.12649431116574 [ 3.08343612  2.01637415 -3.98177108]
5.12125715638267 [ 3.08510157  2.01630263 -3.98183958]
5.116081090217382 [ 3.08675728  2.01623151 -3.98190768]
5.110965400103694 [ 3.0884033   2.01616082 -3.98197538]
5.105909381787141 [ 3.0900397   2.01609054 -3.98204269]
5.100912339228035 [ 3.09166652  2.01602067 -3.9821096 ]
5.095973584505636 [ 3.09328383  2.01595121 -3.98217612]
5.091092437723414 [ 3.09489168  2.01588215 -3.98224225]
5.086268226915435 [ 3.09649012  2.0158135  -3.982308  ]
5.08150028795397 [ 3.09807922  2.01574525 -3.98237336]
5.076787964457914 [ 3.09965901  2.0156774  -3.98243834]
5.072130607702487 [ 3.10122957  2.01560995 -3.98250293]
5.067527576530022 [ 3.10279094  2.01554289 -3.98256

4.758471381579595 [ 3.24725498  2.00933833 -3.98850904]
4.757527018016033 [ 3.24796219  2.00930796 -3.98853813]
4.756593669949844 [ 3.24866528  2.00927776 -3.98856705]
4.755671208891123 [ 3.24936425  2.00924774 -3.9885958 ]
4.754759507848753 [ 3.25005913  2.0092179  -3.98862438]
4.753858441312843 [ 3.25074994  2.00918823 -3.98865279]
4.7529678852375605 [ 3.25143672  2.00915873 -3.98868104]
4.752087717023998 [ 3.25211948  2.00912941 -3.98870912]
4.751217815503297 [ 3.25279824  2.00910025 -3.98873704]
4.750358060919936 [ 3.25347304  2.00907127 -3.9887648 ]
4.74950833491531 [ 3.25414388  2.00904246 -3.98879239]
4.748668520511401 [ 3.25481081  2.00901382 -3.98881982]
4.747838502094674 [ 3.25547383  2.00898534 -3.98884709]
4.747018165400144 [ 3.25613297  2.00895703 -3.9888742 ]
4.746207397495723 [ 3.25678826  2.00892889 -3.98890115]
4.745406086766511 [ 3.25743972  2.00890091 -3.98892795]
4.744614122899666 [ 3.25808736  2.00887309 -3.98895459]
4.743831396869028 [ 3.25873122  2.00884544 -3.98

4.690801537275707 [ 3.31917308  2.00624954 -3.99146708]
4.690646506359927 [ 3.31945962  2.00623723 -3.99147886]
4.690493283797112 [ 3.31974449  2.00622499 -3.99149058]
4.690341848493776 [ 3.32002769  2.00621283 -3.99150223]
4.690192179602466 [ 3.32030924  2.00620074 -3.99151381]
4.690044256519013 [ 3.32058914  2.00618872 -3.99152532]
4.689898058879413 [ 3.3208674   2.00617677 -3.99153677]
4.689753566557316 [ 3.32114404  2.00616488 -3.99154814]
4.689610759661111 [ 3.32141905  2.00615307 -3.99155946]
4.68946961853121 [ 3.32169246  2.00614133 -3.9915707 ]
4.689330123737314 [ 3.32196427  2.00612966 -3.99158188]
4.689192256075794 [ 3.32223449  2.00611805 -3.99159299]
4.68905599656703 [ 3.32250313  2.00610651 -3.99160404]
4.688921326452773 [ 3.32277019  2.00609504 -3.99161503]
4.688788227193574 [ 3.3230357   2.00608364 -3.99162595]
4.688656680466286 [ 3.32329965  2.0060723  -3.99163681]
4.6885266681613915 [ 3.32356206  2.00606103 -3.9916476 ]
4.688398172380725 [ 3.32382293  2.00604983 -3.991

4.6796419509053235 [ 3.34854381  2.0049881  -3.99267511]
4.679617090613493 [ 3.34865855  2.00498317 -3.99267983]
4.679592520303745 [ 3.34877263  2.00497827 -3.99268452]
4.679568236593546 [ 3.34888603  2.0049734  -3.99268919]
4.679544236139889 [ 3.34899878  2.00496856 -3.99269383]
4.679520515638714 [ 3.34911086  2.00496374 -3.99269844]
4.6794970718245334 [ 3.34922229  2.00495896 -3.99270302]
4.679473901469963 [ 3.34933307  2.0049542  -3.99270758]
4.6794510013852 [ 3.3494432   2.00494947 -3.99271211]
4.679428368417721 [ 3.34955268  2.00494477 -3.99271661]
4.679405999451749 [ 3.34966153  2.00494009 -3.99272109]
4.679383891407825 [ 3.34976974  2.00493545 -3.99272554]
4.6793620412424275 [ 3.34987731  2.00493083 -3.99272996]
4.679340445947596 [ 3.34998426  2.00492623 -3.99273436]
4.6793191025503305 [ 3.35009058  2.00492167 -3.99273873]
4.679298008112431 [ 3.35019627  2.00491713 -3.99274308]
4.679277159729876 [ 3.35030135  2.00491261 -3.9927474 ]
4.679256554532604 [ 3.35040582  2.00490813 -3.

array([ 3.35665783,  2.00463961, -3.99300885])

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
lr=LinearRegression()

In [15]:
x.shape

(50, 3)

In [30]:
lr.fit(x.iloc[:,1:],y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [31]:
lr.coef_

array([ 2.00346005, -4.01022363])

In [32]:
lr.intercept_

3.530674802067832