#### Numpy:
    * Introduction
    * Creation
    * Indexing/slicing
    * Mathematical operations on arrays
    * Broadcasting

#### Pandas:
    * Create pandas dataframe
    * Write/read dataframe to/from ext file
    * Dataframe summary commands
    * Dataframe aggregation commands- crosstab, groupby etc
    * Operations with multiple dataframes- merge, concat, append

#### Why numpy arrays?

* Size - Numpy data structures take up less space
* Performance - they have a need for speed and are faster than lists
* Functionality - SciPy and NumPy have optimized functions such as linear algebra operations built in.

For understanding purpose, two dimensional arrays can be understood as list of lists. A bigger list containing multiple lists. Lets create one; that will give you an idea about what are we trying to say:

In [1]:
import numpy as np
import math

# Create a 2D array
b = np.array([[1,2,3],[4,5,6]])   
b.shape

(2, 3)

You can determine dimension of array with attribute shape

In [6]:
b.shape

(2, 3)

Here the first number represents how many internal lists we have and second number represents , how many memebers these internal lists have. Individual elements of these arrays can be accessed by passing indices in square brackets. First represents, which internal list we want to access [ counting starts with 0] and which member of the said list we want to access; is represented by the second index. Lets see few examples 

In [3]:
print(b)
b[0, 0], b[0, 1], b[1, 0]   



[[1 2 3]
 [4 5 6]]


(1, 2, 4)

Next we look at quick ways of creating some arrays with default values

In [5]:
# All zeros
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [6]:
# All ones
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [26]:
# All constants
np.full((2,2), math.pi)

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

In [5]:
# Identity Matrix
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
# Random numbers from [0,1]
np.random.random((4,3))

array([[0.30565049, 0.66194645, 0.75525452],
       [0.89944765, 0.87664374, 0.05877363],
       [0.39781539, 0.06768672, 0.41723791],
       [0.32849486, 0.0917046 , 0.91376251]])

To obtain a number in the interval [a,b), you can simply multiply above with (b-a) and then add a.

In [9]:
# random number from [5,10)
(10-5)*np.random.random()+5

6.1505266545830475

##### Q- Create a 10*10 metrix which contain value between 50-60




### More on accessing arrays with indices
Its not necessary that when you are accessing elements of array; index values have to be continuous . They can be any number as long as they do not go out of range of exsiting element positions.

In [40]:
#Create a sample array
a = np.array([[1,2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
a[[0, 1, 2], [0, 1, 0]]
#here it will access the combination- (0,0), (1,1), (2,0)

array([1, 4, 5])

In [5]:
# another example

a = np.array([(1,2,3), (4,5,6), (7,8,9), (10, 11, 12)])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [2]:
b = np.array([0, 2, 0, 1])
c = np.arange(4)


In [3]:
print (b)
print (c)

[0 2 0 1]
[0 1 2 3]


In [6]:
a[c, b]  # Here it will access elemets (0,1), (1,2), (2,0), (3,1)

array([ 1,  6,  7, 11])

Using index you can access elements as well as modify them

In [67]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
a[c, b] += 10  # Increasing the value by 10 for the selected elements
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

### Conditional Access of arrays
if a here was a single element , writing a>2 wil gegenrate True or False depeneding on whetrher that particular consition was true.

Now when a is a numpy array, that comparison will be done for each element and result will be an array of shape same as a ; containing True/False for each element.

In [70]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
c=a > 2
print(c)

[[False False]
 [ True  True]
 [ True  True]]


We can use , these comparison expressions directly for access. Result is only those elements for which the expression evaluates to True

In [76]:
print(a[c])
print(a[c].shape)

[3 4 5 6]
(4,)


notice that the result is a 1D array.

Lets see if this works with writing mulitple conditions as well. In that process we'll also see that we dont have to store results in one variable and then pass for subsetting. We can instead, write the conditional expression directly for subsetting.

In [10]:
(a>2) & (a<5)

array([[False, False,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [12]:
a[(a>2) & (a<5)] # Elements where flag is True are filtered out

array([3, 4])

### Array Operations

We'll see that you can use ; both normal symbols as well as numpy functions for array operations. Lets look at these operations with examples

In [42]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [43]:
x

array([[1, 2],
       [3, 4]])

In [44]:
y

array([[5, 6],
       [7, 8]])

In [45]:
x+y

array([[ 6,  8],
       [10, 12]])

In [46]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [47]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [48]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [37]:
# element wise multiplication , not matrix multiplication
print(x)
print("~~~~~")

print(y)
print("~~~~~")
print(x * y)

[[1 2]
 [3 4]]
~~~~~
[[5 6]
 [7 8]]
~~~~~
[[ 5 12]
 [21 32]]


In [49]:
#This is also element wise multiplication
np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [39]:
print(x/y)

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [40]:
np.divide(x,y)

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

In general you'll find that , mathematical functions from numpy [being referred as np here ] when applied on array, give back result as an array where that function has been applied on individual elements. These function from package math on the other hand give error when applied to arrays. They only work for scalars.

In [41]:
np.sqrt(x)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [42]:
math.sqrt(x)

TypeError: only length-1 arrays can be converted to Python scalars

In [8]:

v = np.array([9,10])
v.ndim

1

In [74]:
w = np.array([11, 12])
w

array([11, 12])

#### Matrix mutiplication: 
Numpy has interesting matrix multiplication rules
* For 1-D array, it is the sum of multiplication of corresponding elements ie. a[1] * b[1]+a[2] * b[2]+a[3] * b[3]
* For n-D array, it checks the dimensions and proceeds for matrix multiplication. 

In [76]:
# Matrix multiplication
v.dot(w)

219

You can see that result is not what you'd expect from matrix multiplication. This happens because a single dimensional array is not a matrix.

In [46]:
print(v.shape)
print(w.shape)

(2,)
(2,)


We can make them to be 2X1 matrices by manually applying that shape to them

In [77]:
v=v.reshape((1,2))
w=w.reshape((1,2))

Now if you simply try to do v.dot(w) or np.dot(v,w) [both are same] , you will get and error because you can multiple a mtrix of shape 2X1 with a matrix of 2X1 .

In [78]:
np.dot(v,w)

ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [79]:
print('matrix v : ',v)
print('matrix v Transpose:',v.T)
print('matrix w:',w)
print('matrix w Transpose:',w.T)
print('~~~~~~~~~')
print(np.dot(v,w.T))
print('~~~~~~~~~')
print(np.dot(v.T,w))

matrix v :  [[ 9 10]]
matrix v Transpose: [[ 9]
 [10]]
matrix w: [[11 12]]
matrix w Transpose: [[11]
 [12]]
~~~~~~~~~
[[219]]
~~~~~~~~~
[[ 99 108]
 [110 120]]


#### np.multiply performs the element wise multiplication

In [98]:
np.multiply(v.T, w)

array([ 99, 120])

If you leave v to be a single dimensional array . you will simply get an element wise multiplication. Here is an example

In [80]:
print(x)
v=np.array([9,10])
print("~~~~~")
print(v.shape)
print (v)
print (x.dot(v))

[[1 2]
 [3 4]]
~~~~~
(2,)
[ 9 10]
[29 67]


### other functions

In [14]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [53]:
np.sum(x)

10

Using axis option in the function sum , you can some across both the dimension of array separately as well

In [18]:
np.sum(x, axis=0)

array([4, 6])

In [19]:
np.sum(x, axis=1)

array([3, 7])

In [56]:
# Transpose : we have used this one already
x

array([[1, 2],
       [3, 4]])

In [57]:
x.T

array([[1, 3],
       [2, 4]])

####  Numpy broadcasting

So far we have seen that, when we do operations between two arrays; operation happens between corresponding elements of the arrays. Many at times , shape of arrays will not match and correspondence between elements will not be complete. In such case , elements of the smaller array are recycled to makeup for the correspondence.

In [14]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

here v is a smaller array than x, lets see what happens when we do operation between x and v. But before that , we are going to replicate v to make up for the correpondence ourselves and see the result

In [18]:
vv = np.tile(v,(4,1))  # Stack 4 copies of v on top of each other
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [60]:
print(x)
print("~~~~~")
print(vv)
x + vv

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
~~~~~
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

Now lets check what would have been the result if we added just x and v


In [61]:
x + v # produce the same result as x + vv

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

Lets see some more examples of operations between mis matching shape arrays

In [62]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

In [63]:
v.shape

(3,)

In [64]:
w.shape

(2,)

In [65]:
x = np.array([[1,2,3], [4,5,6]]) # x has shape (2,3])
x.shape

(2, 3)

In [66]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
print(x)
print("~~~~~")
print(v)
x + v

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
~~~~~
[[1]
 [2]
 [3]
 [4]]


array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

What we see here is known as broadcasting of values. But dimensions need to be compatible for that too

In [31]:
v=np.array([1,2])

In [69]:
x+v

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [70]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [11]:
print (a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
print (a.reshape(6,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [13]:
print (a.reshape(2,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [71]:
print(x)
print("~~~~~")
print(w)
x.T + w

[[1 2 3]
 [4 5 6]]
~~~~~
[4 5]


array([[ 5,  9],
       [ 6, 10],
       [ 7, 11]])

In [72]:
(x.T + w).T



array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [73]:
x + np.reshape(w, (2, 1))

array([[ 5,  6,  7],
       [ 9, 10, 11]])

### Numpy additional questions
#### Q- Find out the difference between np.arange and np.linspace functions and how can we use these
#### Q- Find out the difference between np.max and np.argmax functions and how can we use these
#### Q- Find out the difference between np.sort and np.argsort functions and how can we use these

## Pandas Data.Frames
Now that we understand how to work with numpay arrays, lets gradute to next level where ,we learn to work with pandas data frames.

In [32]:
import pandas as pd
import numpy as np

In [22]:
%matplotlib inline

Above line is written so that visualisation produced by package matplot lib is visible in the notebook.

#### Create a dataframe using lists

In [34]:
cities=["Delhi","Mumbai","Kolkata","Chennai"]
code = [11,22,33,44]

mydata=list(zip(cities,code))

zip combines corresponding elements of an iterable into 
tuples

In [35]:
mydata

[('Delhi', 11), ('Mumbai', 22), ('Kolkata', 33), ('Chennai', 44)]

now lets convert this to a pandas data frame which comes with lot of useful and intuitive properties which makes our job easy when working with dataframes in general. If you have worked with R before, then you'd notice that pandas dataframes works very similar to R's data frames.

In [36]:
df = pd.DataFrame(data=mydata,columns=["cities","codes"])
df

cities  codes
0    Delhi     11
1   Mumbai     22
2  Kolkata     33
3  Chennai     44

to write a data frame to csv file , you can use function to_csv. In the function you need to set option index=False in order to avoid writing rownumbers to csv file and header=True , in order to write variables names in the first row of the csv file.

if you simply provide the file name, it will be written to where your .ipynb/.py file is. In case you want to write the file to a specific location then you'd need to mention the file name with complete path.

In [37]:
df.to_csv("mydata.csv",index=False,header=False)

You can use function ExcelWriter to creater a writer object for an excel file. and then use function to_excel with data frame to write data to excel file. Here is an example

In [38]:
writer=pd.ExcelWriter("mydata.xlsx")

df.to_excel(writer,"Sheet1",index=False)
df.to_excel(writer,"Sheet2")

#### Create dataframe from dictionary of lists

In [5]:
data = {'Name':['Tom', 'nick', 'krish', 'jack'], 'Age':[20, 21, 19, 18]} 

In [8]:
df_from_dict = pd.DataFrame(data) 

In [9]:
print (df_from_dict)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18


#### Creating Dataframe from list of dicts

In [19]:
data = [{'a': 1, 'b': 2, 'c':3}, {'a':10, 'b': 20, 'c': 30}] 

In [25]:
df_from_list_of_dict = pd.DataFrame(data) 


In [26]:
df_from_list_of_dict

a   b   c
0   1   2   3
1  10  20  30

To read from a csv file, we'll be using function read_csv. we can create a separate string first with complete path name and then use it in the function or anywhere else.

In [40]:
# myfile=r'/Users/lalitsachan/Dropbox/March onwards/Python Data Science/Data/bank-full.csv'
myfile= '/home/fractaluser/Documents/Edvancer/ML//WeekII//bank-full.csv'
bd=pd.read_csv(myfile,sep=",")

In [41]:
bd.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no      NaN     yes   no   
1   44    technician   single  secondary      no      NaN     yes   no   
2   33  entrepreneur  married  secondary      no      NaN     yes  yes   
3   47   blue-collar  married    unknown      no      NaN     yes   no   
4   33       unknown   single    unknown      no      NaN      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

attribute dtype contains information regarding data type for all the columns

In [36]:
bd.dtypes

job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

dtype object refers to categorical variables for columns. You can check dtype for individual columns as follows :

In [84]:
bd["month"].dtype

dtype('O')

using function `head` you can lok at first few observations in the data which gives an idea about whether data was imported properly to python or not.

In [85]:
bd.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

Function describe quickly prepares summary for numeric columns in the data.

In [86]:
bd.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

you can access specific summary statstic as well using respective functions. For example to find median of all numeric columns you do this :

In [44]:
bd.median()

balance     448.0
day          16.0
duration    180.0
campaign      2.0
pdays        -1.0
previous      0.0
Name: 0.5, dtype: float64

these describe and individual summary functions can be used with individual columns or subset of data too.

The need for custom functions is minimal unless you have very specific requirements. The full range of basic statistics that are quickly calculable and built into the base Pandas package are:

|Function	|Description|
|-----------|-----------|
|count	|Number of non-null observations|
|sum	|Sum of values|
|mean	|Mean of values|
|mad	|Mean absolute deviation|
|median	|Arithmetic median of values|
|min	|Minimum|
|max	|Maximum|
|mode	|Mode|
|abs	|Absolute Value|
|prod	|Product of values|
|std	|Unbiased standard deviation|
|var	|Unbiased variance|
|sem	|Unbiased standard error of the mean|
|skew	|Unbiased skewness (3rd moment)|
|kurt	|Unbiased kurtosis (4th moment)|
|quantile	|Sample quantile (value at %)|
|cumsum	|Cumulative sum|
|cumprod	|Cumulative product|
|cummax	|Cumulative maximum|
|cummin	|Cumulative minimum|

For categorical variables, these kind of numeric summaries can not be calculated. As a summary we need to look at frequency of levels/categories of categorical variable. Which can be achieved through function value_counts(). This function doesn't work with a data frame.

In [22]:
bd["job"].value_counts()

blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: job, dtype: int64

You can use function select_dtypes for extracting a specific type of data columns from a dataframe as subset

In [24]:
bd_cat_data=bd.select_dtypes(['object'])

attribute columns contains all column names of a data.frame

In [26]:
print (bd_cat_data.columns)

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome', 'y'],
      dtype='object')


In [ ]:
for c in bd_cat_data.columns:
    print(bd[c].value_counts())

In [42]:
### Missig value count
for i in bd.columns:
    print (i, bd[i].isna().sum())

age 0
job 0
marital 0
education 0
default 0
balance 44
housing 0
loan 0
contact 0
day 0
month 0
duration 0
campaign 0
pdays 0
previous 0
poutcome 0
y 0


In [34]:
#Introduce some NaN values in balance column. 

In [43]:
bd['balance_2'] = bd['balance'].fillna(np.mean(bd['balance']),inplace=False)   
#inplace=False will not change the original column,
# instead it will return the changed column, which we are saving in 'balance_2'

In [44]:
#bd['balance'].fillna(np.mean(bd['balance']),inplace=True)
#inplace= True will change the origianl column. 
# We are commenting this because we need the column balance with some NaN values. 

In [45]:
bd.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no      NaN     yes   no   
1   44    technician   single  secondary      no      NaN     yes   no   
2   33  entrepreneur  married  secondary      no      NaN     yes  yes   
3   47   blue-collar  married    unknown      no      NaN     yes   no   
4   33       unknown   single    unknown      no      NaN      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  \
0  unknown    5   may       261         1     -1         0  unknown  no   
1  unknown    5   may       151         1     -1         0  unknown  no   
2  unknown    5   may        76         1     -1         0  unknown  no   
3  unknown    5   may        92         1     -1         0  unknown  no   
4  unknown    5   may       198         1     -1         0  unknown  no   

    balance_2  
0  1363.07583  
1  1363.07583  
2  1363.07583  
3  1363.07583  
4  1363.07583

In [46]:
bd['balance_3']= bd['balance'].fillna(method= 'bfill')
#This will create a new column- balance_3 and which will have the NaN values backfilled. 
# i.e. value from the below row

In [20]:
bd.head(50)

age            job   marital  education default  balance housing loan  \
0    58     management   married   tertiary      no      NaN     yes   no   
1    44     technician    single  secondary      no      NaN     yes   no   
2    33   entrepreneur   married  secondary      no      NaN     yes  yes   
3    47    blue-collar   married    unknown      no      NaN     yes   no   
4    33        unknown    single    unknown      no      NaN      no   no   
5    35     management   married   tertiary      no      NaN     yes   no   
6    28     management    single   tertiary      no      NaN     yes  yes   
7    42   entrepreneur  divorced   tertiary     yes      NaN     yes   no   
8    58        retired   married    primary      no      NaN     yes   no   
9    43     technician    single  secondary      no      NaN     yes   no   
10   41         admin.  divorced  secondary      no      NaN     yes   no   
11   29         admin.    single  secondary      no      NaN     yes   no   
12   53     technician   married  secondary      no      NaN     yes   no   
13   58     technician   married    unknown      no      NaN     yes   no   
14   57       services   married  secondary      no      NaN     yes   no   
15   51        retired   married    primary      no      NaN     yes   no   
16   45         admin.    single    unknown      no      NaN     yes   no   
17   57    blue-collar   married    primary      no      NaN     yes   no   
18   60        retired   married    primary      no      NaN     yes   no   
19   33       services   married  secondary      no      NaN     yes   no   
20   28    blue-collar   married  secondary      no      NaN     yes  yes   
21   56     management   married   tertiary      no      NaN     yes   no   
22   32    blue-collar    single    primary      no      NaN     yes  yes   
23   25       services   married  secondary      no      NaN     yes   no   
24   40        retired   married    primary      no      NaN     yes  yes   
25   44         admin.   married  secondary      no      NaN     yes   no   
26   39     management    single   tertiary      no      NaN     yes   no   
27   52   entrepreneur   married  secondary      no      NaN     yes  yes   
28   46     management    single  secondary      no      NaN     yes   no   
29   36     technician    single  secondary      no      NaN     yes  yes   
30   57     technician   married  secondary      no      NaN      no  yes   
31   49     management   married   tertiary      no      NaN     yes   no   
32   60         admin.   married  secondary      no      NaN     yes  yes   
33   59    blue-collar   married  secondary      no      NaN     yes   no   
34   51     management   married   tertiary      no      NaN     yes   no   
35   57     technician  divorced  secondary      no      NaN     yes   no   
36   25    blue-collar   married  secondary      no      NaN     yes   no   
37   53     technician   married  secondary      no      NaN      no   no   
38   36         admin.  divorced  secondary      no      NaN     yes   no   
39   37         admin.    single  secondary      no      NaN     yes   no   
40   44       services  divorced  secondary      no      NaN     yes   no   
41   50     management   married  secondary      no      NaN     yes   no   
42   60    blue-collar   married    unknown      no      NaN     yes   no   
43   54        retired   married  secondary      no      NaN     yes   no   
44   58        retired   married    unknown      no     96.0     yes   no   
45   36         admin.    single    primary      no   -171.0     yes   no   
46   58  self-employed   married   tertiary      no   -364.0     yes   no   
47   44     technician   married  secondary      no      0.0     yes   no   
48   55     technician  divorced  secondary      no      0.0      no   no   
49   29     management    single   tertiary      no      0.0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  \


##### Q- Explore the option of 'ffill' for the same data

Crosstab works like excel pivot table. Their use is as follows:

In [48]:
pd.crosstab(bd["y"],bd["job"])
# unique values of bd['y'] will come in the rows
# unique values of bd['job'] will come in the rows

job  admin.  blue-collar  entrepreneur  housemaid  management  retired  \
y                                                                        
no     4540         9024          1364       1131        8157     1748   
yes     631          708           123        109        1301      516   

job  self-employed  services  student  technician  unemployed  unknown  
y                                                                       
no            1392      3785      669        6757        1101      254  
yes            187       369      269         840         202       34

In [49]:
#Crosstab with values option
pd.crosstab(bd["y"],bd["job"], values=bd['duration'], aggfunc='mean')
#Now values are filled with mean of 'duration' for each combination of 'job' and 'y'

job      admin.  blue-collar  entrepreneur   housemaid  management  \
y                                                                    
no   211.285903   230.541445    221.439883  216.251105  214.819909   
yes  503.114105   675.355932    642.991870  552.688073  499.620292   

job     retired  self-employed    services     student  technician  \
y                                                                    
no   236.303204     225.721264  223.979921  197.784753  217.285038   
yes  460.325581     584.042781  621.804878  368.200743  539.433333   

job  unemployed     unknown  
y                            
no   239.533152  205.673228  
yes  555.673267  476.205882

In [50]:
#Setting margins=True will give you subtotals
#You can also haev multiple levels while populating crosstabs
pd.crosstab([bd["y"],bd["default"]],bd["job"],margins=True)

job          admin.  blue-collar  entrepreneur  housemaid  management  \
y   default                                                             
no  no         4469         8838          1315       1110        8001   
    yes          71          186            49         21         156   
yes no          628          693           117        108        1293   
    yes           3           15             6          1           8   
All            5171         9732          1487       1240        9458   

job          retired  self-employed  services  student  technician  \
y   default                                                          
no  no          1723           1361      3714      666        6637   
    yes           25             31        71        3         120   
yes no           515            185       365      269         830   
    yes            1              2         4        0          10   
All             2264           1579      4154      938        7597   

job          unemployed  unknown    All  
y   default                              
no  no             1073      252  39159  
    yes              28        2    763  
yes no              200       34   5237  
    yes               2        0     52  
All                1303      288  45211

#### Similar functions can be performed with groupby functions

In [51]:
bd["age"].mean()

40.93621021432837

In [52]:
bd.groupby('job')["age"].mean()

job
admin.           39.289886
blue-collar      40.044081
entrepreneur     42.190989
housemaid        46.415323
management       40.449567
retired          61.626767
self-employed    40.484484
services         38.740250
student          26.542644
technician       39.314598
unemployed       40.961627
unknown          47.593750
Name: age, dtype: float64

this gives us average age across different job categories . You can use any other statistical summary function given in the table discussed previously in this module

you can calculate multiple groupwise summary stats for different columns also. Lets look at example below:

In [53]:
bd.groupby(['housing','loan'])["age","balance"].mean()

age      balance
housing loan                        
no      no    43.260695  1737.808859
        yes   42.417449   752.683241
yes     no    39.142947  1257.385818
        yes   39.329059   789.615279

you can use function agg with grouped data to calculate different summary stats for different columns. Here is an example

In [54]:
bd.groupby(['housing','loan']).agg({'age':'mean','duration':'max','balance':'sum'})

age  duration     balance
housing loan                                 
no      no    43.260695      3881  29893788.0
        yes   42.417449      3422   2164717.0
yes     no    39.142947      4918  26065608.0
        yes   39.329059      3253   3441933.0

### Putting conditional filters on a dataframe

In [55]:
bd.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no      NaN     yes   no   
1   44    technician   single  secondary      no      NaN     yes   no   
2   33  entrepreneur  married  secondary      no      NaN     yes  yes   
3   47   blue-collar  married    unknown      no      NaN     yes   no   
4   33       unknown   single    unknown      no      NaN      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  \
0  unknown    5   may       261         1     -1         0  unknown  no   
1  unknown    5   may       151         1     -1         0  unknown  no   
2  unknown    5   may        76         1     -1         0  unknown  no   
3  unknown    5   may        92         1     -1         0  unknown  no   
4  unknown    5   may       198         1     -1         0  unknown  no   

    balance_2  balance_3  
0  1363.07583       96.0  
1  1363.07583       96.0  
2  1363.07583       96.0  
3  1363.07583       96.0  
4  1363.07583       96.0

In [22]:
### Let us create a dataframe where only age < 40 rows are considered 
#Creating the filter
bd['age']>40

0         True
1         True
2        False
3         True
4        False
5        False
6        False
7         True
8         True
9         True
10        True
11       False
12        True
13        True
14        True
15        True
16        True
17        True
18        True
19       False
20       False
21        True
22       False
23       False
24       False
25        True
26       False
27        True
28        True
29       False
         ...  
45181     True
45182    False
45183     True
45184     True
45185     True
45186     True
45187    False
45188    False
45189    False
45190    False
45191     True
45192    False
45193    False
45194     True
45195     True
45196    False
45197    False
45198    False
45199    False
45200    False
45201     True
45202    False
45203    False
45204     True
45205    False
45206     True
45207     True
45208     True
45209     True
45210    False
Name: age, Length: 45211, dtype: bool

In [23]:
#Creating dataframe out of that filter
bd[(bd['age']>40) & (bd['marital']=='married')]

1653.7098814755627

In [56]:
### Suppose you want to extract only 2 columns out of this filtered dataframe- marital and loan
bd[bd['age']>40][['marital','loan']]

marital loan
0       married   no
1        single   no
3       married   no
7      divorced   no
8       married   no
9        single   no
10     divorced   no
12      married   no
13      married   no
14      married   no
15      married   no
16       single   no
17      married   no
18      married   no
21      married   no
25      married   no
27      married  yes
28       single   no
30      married  yes
31      married   no
32      married  yes
33      married   no
34      married   no
35     divorced   no
37      married   no
40     divorced   no
41      married   no
42      married   no
43      married   no
44      married   no
...         ...  ...
45147  divorced   no
45150   married   no
45151    single  yes
45152   married   no
45153   married  yes
45154   married   no
45155   married   no
45157   married   no
45159   married   no
45163   married   no
45166    single   no
45167   married   no
45168   married   no
45174   married   no
45176   married   no
45180   married   no
45181   married   no
45183   married   no
45184   married   no
45185   married   no
45186   married   no
45191  divorced   no
45194   married  yes
45195   married   no
45201   married   no
45204   married   no
45206   married   no
45207  divorced   no
45208   married   no
45209   married   no

[20494 rows x 2 columns]

#### Accessing a particular element of pandas dataframe- Slicing and indexing

In [68]:
bd.iloc[2,4] # This will give us the value of 3rd row and 5th column

'no'

In [69]:
#Similarly, you can access the element by index and column name- using loc

In [71]:
bd.loc[2,'default']  #Note that 2 here is not row number, but index

'no'

In [72]:
# Let us read the same file with different index column to understand the difference

In [73]:
bd_new= pd.read_csv('bank-full.csv', index_col = 0)

In [75]:
bd_new.head()  #Note that index is 'age' column now

job  marital  education default  balance housing loan  contact  \
age                                                                            
58     management  married   tertiary      no      NaN     yes   no  unknown   
44     technician   single  secondary      no      NaN     yes   no  unknown   
33   entrepreneur  married  secondary      no      NaN     yes  yes  unknown   
47    blue-collar  married    unknown      no      NaN     yes   no  unknown   
33        unknown   single    unknown      no      NaN      no   no  unknown   

     day month  duration  campaign  pdays  previous poutcome   y  
age                                                               
58     5   may       261         1     -1         0  unknown  no  
44     5   may       151         1     -1         0  unknown  no  
33     5   may        76         1     -1         0  unknown  no  
47     5   may        92         1     -1         0  unknown  no  
33     5   may       198         1     -1         0  unknown  no

In [76]:
bd_new.loc[58, 'balance']
#Here 58 is the index, i.e. 'age' of the person, and not row number

age
58        NaN
58        NaN
58        NaN
58       96.0
58     -364.0
58      235.0
58     1065.0
58       76.0
58     1387.0
58     1667.0
58       29.0
58        0.0
58      469.0
58      -11.0
58     5435.0
58       68.0
58     1109.0
58      268.0
58      211.0
58      786.0
58       44.0
58        5.0
58      613.0
58      771.0
58      -91.0
58       47.0
58      127.0
58     1166.0
58      146.0
58     7495.0
       ...   
58     1625.0
58     7554.0
58      589.0
58     2155.0
58      169.0
58      473.0
58     4606.0
58    11494.0
58     1016.0
58     1965.0
58      307.0
58     1119.0
58      496.0
58      226.0
58      169.0
58     1230.0
58      139.0
58      256.0
58     3109.0
58     1318.0
58     1299.0
58     2155.0
58      169.0
58        0.0
58     2986.0
58       99.0
58     1333.0
58     3337.0
58     3927.0
58      742.0
Name: balance, Length: 740, dtype: float64

#### Let us see some functions by which you can combine multiple dataframes
### df.concat

In [77]:
import numpy as np

In [78]:
#Let us create a temporary dataframe
gen= np.random.choice([0,1],size= bd.shape[0])
salary = 500*np.random.random([bd.shape[0]])+1000
salary_df= pd.DataFrame(data= list(zip(gen,salary)), 
                        columns=['gender', 'salary'])

In [79]:
concat_horiz_df= pd.concat([bd,salary_df], axis =1)
#This will combine 2 dataframes horizontally ie. column wise

In [80]:
print (salary_df.shape)
print (bd.shape)
print (concat_horiz_df.shape)

(45211, 2)
(45211, 19)
(45211, 21)


In [81]:
concat_horiz_df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no      NaN     yes   no   
1   44    technician   single  secondary      no      NaN     yes   no   
2   33  entrepreneur  married  secondary      no      NaN     yes  yes   
3   47   blue-collar  married    unknown      no      NaN     yes   no   
4   33       unknown   single    unknown      no      NaN      no   no   

   contact  day     ...      duration  campaign  pdays  previous  poutcome  \
0  unknown    5     ...           261         1     -1         0   unknown   
1  unknown    5     ...           151         1     -1         0   unknown   
2  unknown    5     ...            76         1     -1         0   unknown   
3  unknown    5     ...            92         1     -1         0   unknown   
4  unknown    5     ...           198         1     -1         0   unknown   

    y   balance_2  balance_3  gender       salary  
0  no  1363.07583       96.0       1  1242.466775  
1  no  1363.07583       96.0       1  1288.540855  
2  no  1363.07583       96.0       1  1181.449880  
3  no  1363.07583       96.0       1  1409.760957  
4  no  1363.07583       96.0       1  1030.652425  

[5 rows x 21 columns]

In [82]:
#created new dataframe
bd_head = bd.head(100)

In [83]:
concat_vert_df= pd.concat([bd, bd_head], axis= 0)

In [84]:
print (bd.shape)
print (bd_head.shape)
print (concat_vert_df.shape)

(45211, 19)
(100, 19)
(45311, 19)


##### We see that dataframe is verticaly concatenated

### df.append

In [86]:
df_add_row = bd.append(bd_head,verify_integrity=False)

In [87]:
print (df_add_row.shape)

(45311, 19)


##### Q- Check what happens when dataframes with different columns are appended. 

### df.merge()

In [88]:
#Create a new dataframe
gen= np.array([0,1])
fixed_salary = 500*np.random.random([2])+1000

In [89]:
fixed_salary_df= pd.DataFrame(data= list(zip(gen,fixed_salary)), 
                              columns=['gender', 'fixed_salary'])

In [90]:
mapped_salary = pd.merge(concat_horiz_df, fixed_salary_df, 
                         left_on = 'gender', right_on = 'gender',
                         how= 'left')

In [91]:
print (concat_horiz_df.shape)
print (fixed_salary_df.shape)
print (mapped_salary.shape)

(45211, 21)
(2, 2)
(45211, 22)


In [92]:
mapped_salary.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no      NaN     yes   no   
1   44    technician   single  secondary      no      NaN     yes   no   
2   33  entrepreneur  married  secondary      no      NaN     yes  yes   
3   47   blue-collar  married    unknown      no      NaN     yes   no   
4   33       unknown   single    unknown      no      NaN      no   no   

   contact  day      ...      campaign  pdays  previous  poutcome   y  \
0  unknown    5      ...             1     -1         0   unknown  no   
1  unknown    5      ...             1     -1         0   unknown  no   
2  unknown    5      ...             1     -1         0   unknown  no   
3  unknown    5      ...             1     -1         0   unknown  no   
4  unknown    5      ...             1     -1         0   unknown  no   

    balance_2 balance_3  gender       salary  fixed_salary  
0  1363.07583      96.0       1  1242.466775   1366.798622  
1  1363.07583      96.0       1  1288.540855   1366.798622  
2  1363.07583      96.0       1  1181.449880   1366.798622  
3  1363.07583      96.0       1  1409.760957   1366.798622  
4  1363.07583      96.0       1  1030.652425   1366.798622  

[5 rows x 22 columns]