In [1]:
import pandas as pd
import numpy as np

In [2]:
x1=np.random.randint(low=1,high=20,size=(50,))


x2=np.random.randint(low=1,high=20,size=(50,))

In [3]:
y=3+2*x1-4*x2+np.random.random((50,))

In [4]:
y

array([ 15.11598805,  11.08734002, -10.74731623,  13.80425567,
       -22.08363814, -12.76399634, -38.76974939,  17.06629496,
       -28.12961844,   3.00523262, -30.23824294,  -4.98848195,
       -30.58004004,  11.09532423,  -4.53216013,   3.83180755,
       -56.2451756 , -58.35958594, -40.37620405, -46.69153251,
       -10.21822851, -20.5270456 ,  19.89214393,   7.40154641,
       -42.44095261, -64.19965056, -26.72900597, -52.90528946,
         3.13259097,  31.47540172, -30.90871296, -12.60379874,
         9.808238  , -38.74489534, -62.53056491, -22.67413174,
        17.89271663, -36.54647252, -26.59147214,  -6.90887451,
       -32.97265243, -30.1993899 , -56.58741345,  11.02211504,
       -10.24229196,   1.64441471, -26.57701932, -58.37679472,
        -4.46134771, -18.12013119])

In [5]:
x1

array([16, 10, 19,  9,  7, 14, 13,  9,  2,  2,  1, 10, 11, 14, 16, 14,  4,
        3, 10,  3, 17,  4, 18, 12, 11,  2,  9, 10, 12, 16, 19, 10, 11,  7,
        3, 13, 15, 16,  5,  7,  4, 19,  6, 10,  9, 17, 19,  1, 18,  9])

In [6]:
x2

array([ 5,  3, 13,  2, 10, 11, 17,  1,  9,  1,  9,  7, 14,  5, 10,  7, 17,
       17, 16, 14, 12,  8,  5,  5, 17, 18, 12, 19,  6,  1, 18,  9,  4, 14,
       18, 13,  4, 18, 10,  6, 11, 18, 18,  3,  8,  9, 17, 16, 11, 10])

In [7]:


x=pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})

w=np.zeros(x.shape[1])

In [8]:
def myprediction(features,weights):

    predictions=np.dot(features,weights)
    return(predictions)

myprediction(x,w)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
def myerror(target,features,weights):
    error=target-myprediction(features,weights)
    return(error)

In [10]:
def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error)
    return(cost)

mycost(y,x,w)


47167.412023718935

In [11]:
def gradient(target,features,weights):
    
    error=myerror(target,features,weights)
    
    gradient=-np.dot(features.T,error)# we are using transpose here because we take sqaure of error to get gradient and Transpose is used to get square of matrix
    
    return(gradient)

gradient(y,x,w)

array([  899.29646746,  5980.3016305 , 15567.99022523])

In [25]:
def my_lr(target,features,learning_rate):
    
    weights=np.zeros(features.shape[1])
    
    for i in np.arange(100000):
        weights -= learning_rate*gradient(target,features,weights)
        weights = weights - learning_rate*gradient(target,features,weights)
        weights[0] -=10*learning_rate*gradient(target,features,weights)[0] # if you comment this out , your coefficient estimates will not be as good as sklearn, why?
        if i%100==0: #after 1000 iteration we are printing cost
            print(mycost(target,features,weights),weights)
    return(weights)

my_lr(y,x,0.0000001)

47054.40606572873 [-0.00107678 -0.00119482 -0.00311218]
37864.09556227696 [-0.09588688 -0.09723155 -0.28743214]
31728.52978108381 [-0.16907835 -0.15426107 -0.52618296]
27478.529598343426 [-0.22544263 -0.18147345 -0.72892327]
24403.49384443777 [-0.2687096  -0.18600583 -0.90311059]
22070.841188701972 [-0.30178274 -0.1733977  -1.0545663 ]
20216.586409903415 [-0.32692223 -0.14794541 -1.18783764]
18679.02369800708 [-0.34588747 -0.11297807 -1.30647953]
17358.532727440775 [-0.36004801 -0.07107227 -1.4132739 ]
16193.215222965759 [-0.37046997 -0.02421934 -1.51040056]
15144.12499878164 [-0.37798321  0.02604462 -1.59957011]
14186.31189029567 [-0.38323371  0.0785374  -1.68212747]
13303.389177041676 [-0.38672428  0.13235189 -1.75913252]
12484.23652073797 [-0.38884632  0.18679468 -1.83142282]
11720.997302478328 [-0.38990448  0.24133839 -1.8996625 ]
11007.860634669196 [-0.39013586  0.29558443 -1.96438028]
10340.319143687078 [-0.38972502  0.34923415 -2.02599914]
9714.7153149496 [-0.3888156   0.4020663

75.30285603019077 [-0.07313002  2.11714593 -3.81637307]
75.05340794091833 [-0.07081174  2.11794575 -3.81735238]
74.81369392677752 [-0.06849507  2.11871791 -3.81830445]
74.58312945242778 [-0.06618003  2.11946326 -3.81923013]
74.36116550870054 [-0.06386659  2.12018264 -3.82013022]
74.14728645286198 [-0.06155477  2.12087684 -3.82100551]
73.94100798017172 [-0.05924455  2.12154665 -3.82185677]
73.74187521875662 [-0.05693593  2.12219282 -3.82268474]
73.54946094030456 [-0.05462892  2.12281608 -3.82349013]
73.36336387953577 [-0.0523235   2.12341714 -3.82427365]
73.1832071558382 [-0.05001967  2.12399669 -3.82503595]
73.00863679085728 [-0.04771743  2.1245554  -3.8257777 ]
72.83932031620547 [-0.04541679  2.12509391 -3.82649953]
72.67494546581544 [-0.04311772  2.12561284 -3.82720204]
72.51521894778787 [-0.04082024  2.12611281 -3.82788585]
72.3598652909017 [-0.03852434  2.1265944  -3.82855151]
72.20862576125097 [-0.03623002  2.12705817 -3.82919959]
72.0612573447421 [-0.03393727  2.12750469 -3.82983

60.42631626189472 [ 0.25344218  2.13209537 -3.85859601]
60.3513156156034 [ 0.25554057  2.13201495 -3.85869442]
60.27641570360814 [ 0.25763757  2.13193432 -3.85879252]
60.20161633860859 [ 0.25973317  2.13185349 -3.8588903 ]
60.126917336786775 [ 0.26182737  2.13177247 -3.85898777]
60.052318517605315 [ 0.26392017  2.13169126 -3.85908495]
59.97781970361946 [ 0.26601158  2.13160988 -3.85918183]
59.90342072029864 [ 0.2681016   2.13152832 -3.85927843]
59.82912139586058 [ 0.27019023  2.13144661 -3.85937476]
59.754921561113974 [ 0.27227746  2.13136474 -3.85947081]
59.68082104931208 [ 0.2743633   2.13128272 -3.8595666 ]
59.60681969601407 [ 0.27644776  2.13120055 -3.85966214]
59.53291733895554 [ 0.27853082  2.13111825 -3.85975742]
59.459113817926536 [ 0.2806125   2.13103582 -3.85985246]
59.38540897465682 [ 0.28269279  2.13095327 -3.85994726]
59.31180265270865 [ 0.28477169  2.13087059 -3.86004182]
59.23829469737592 [ 0.28684921  2.13078781 -3.86013616]
59.16488495558859 [ 0.28892535  2.13070491 -3

50.408760295628795 [ 0.5473789   2.1198942  -3.87146509]
50.34711190555059 [ 0.54928152  2.11981351 -3.87154671]
50.2855455972727 [ 0.55118288  2.11973287 -3.87162828]
50.224061261502 [ 0.55308297  2.11965228 -3.87170979]
50.162658789091495 [ 0.55498179  2.11957175 -3.87179124]
50.10133807103938 [ 0.55687935  2.11949126 -3.87187263]
50.04009899848951 [ 0.55877565  2.11941083 -3.87195397]
49.978941462731065 [ 0.56067068  2.11933045 -3.87203526]
49.917865355197975 [ 0.56256445  2.11925012 -3.87211648]
49.85687056746913 [ 0.56445696  2.11916984 -3.87219765]
49.795956991267985 [ 0.56634821  2.11908961 -3.87227877]
49.73512451846222 [ 0.5682382   2.11900943 -3.87235983]
49.674373041063774 [ 0.57012693  2.11892931 -3.87244083]
49.61370245122849 [ 0.57201441  2.11884923 -3.87252178]
49.553112641256185 [ 0.57390063  2.11876921 -3.87260267]
49.49260350358997 [ 0.57578559  2.11868924 -3.87268351]
49.43217493081633 [ 0.57766929  2.11860932 -3.87276429]
49.37182681566527 [ 0.57955174  2.11852946 -

42.17319900099591 [ 0.81389514  2.10858207 -3.88288957]
42.12251584571291 [ 0.81562027  2.10850883 -3.8829635 ]
42.07190017248793 [ 0.81734426  2.10843564 -3.88303738]
42.02135189147205 [ 0.8190671   2.1083625  -3.88311122]
41.97087091293598 [ 0.82078879  2.1082894  -3.883185  ]
41.92045714726996 [ 0.82250934  2.10821636 -3.88325874]
41.87011050498344 [ 0.82422874  2.10814336 -3.88333243]
41.81983089670495 [ 0.825947    2.10807042 -3.88340606]
41.7696182331821 [ 0.82766411  2.10799752 -3.88347965]
41.71947242528135 [ 0.82938008  2.10792467 -3.88355319]
41.669393383987845 [ 0.8310949   2.10785187 -3.88362668]
41.619381020405214 [ 0.83280858  2.10777911 -3.88370012]
41.569435245755436 [ 0.83452113  2.10770641 -3.88377352]
41.5195559713788 [ 0.83623253  2.10763375 -3.88384686]
41.46974310873343 [ 0.83794279  2.10756114 -3.88392016]
41.41999656939552 [ 0.83965191  2.10748858 -3.8839934 ]
41.370316265058975 [ 0.8413599   2.10741607 -3.8840666 ]
41.32070210753517 [ 0.84306674  2.10734361 -3.

35.444198730266336 [ 1.05398424  2.09838917 -3.89317881]
35.402474898542295 [ 1.05554949  2.09832271 -3.89324589]
35.36080661999003 [ 1.05711369  2.09825631 -3.89331292]
35.319193820643534 [ 1.05867686  2.09818994 -3.89337991]
35.27763642663473 [ 1.06023899  2.09812362 -3.89344686]
35.23613436419453 [ 1.06180007  2.09805735 -3.89351376]
35.1946875596515 [ 1.06336012  2.09799112 -3.89358062]
35.15329593943276 [ 1.06491912  2.09792493 -3.89364743]
35.11195943006305 [ 1.06647709  2.09785878 -3.8937142 ]
35.070677958164964 [ 1.06803402  2.09779269 -3.89378092]
35.02945145045912 [ 1.06958992  2.09772663 -3.8938476 ]
34.988279833763386 [ 1.07114478  2.09766062 -3.89391423]
34.94716303499308 [ 1.0726986   2.09759465 -3.89398082]
34.90610098116098 [ 1.07425139  2.09752873 -3.89404737]
34.86509359937682 [ 1.07580314  2.09746285 -3.89411387]
34.824140816847844 [ 1.07735386  2.09739701 -3.89418033]
34.783242560877525 [ 1.07890355  2.09733122 -3.89424674]
34.74239875886691 [ 1.08045221  2.09726547

29.90469209537499 [ 1.27182177  2.08914092 -3.90251441]
29.870343836589157 [ 1.27324195  2.08908063 -3.90257527]
29.83604131077297 [ 1.27466119  2.08902037 -3.9026361 ]
29.801784457034977 [ 1.27607948  2.08896016 -3.90269688]
29.767573214565417 [ 1.27749683  2.08889999 -3.90275762]
29.733407522634927 [ 1.27891323  2.08883985 -3.90281832]
29.699287320595495 [ 1.28032869  2.08877976 -3.90287898]
29.665212547879523 [ 1.28174321  2.08871971 -3.9029396 ]
29.63118314400016 [ 1.28315678  2.08865969 -3.90300018]
29.597199048551104 [ 1.28456942  2.08859972 -3.90306072]
29.563260201206464 [ 1.28598111  2.08853979 -3.90312122]
29.529366541720776 [ 1.28739186  2.0884799  -3.90318168]
29.49551800992847 [ 1.28880168  2.08842004 -3.9032421 ]
29.461714545744584 [ 1.29021055  2.08836023 -3.90330248]
29.427956089163665 [ 1.29161849  2.08830045 -3.90336281]
29.394242580260418 [ 1.29302549  2.08824072 -3.90342311]
29.36057395918928 [ 1.29443155  2.08818103 -3.90348337]
29.326950166184524 [ 1.29583668  2.0

array([ 1.4330265 ,  2.08229701, -3.90942297])

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
lr=LinearRegression()

In [28]:
x.shape

(50, 3)

In [41]:
lr.fit(x.iloc[:,1:],y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [32]:
lr.coef_

array([ 1.99860279, -3.99390776])

In [33]:
lr.intercept_

3.4043994898746206